/**
 * ReservApp.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemStatus } from '../models/OrderItemStatus';
import { OrderItemType } from '../models/OrderItemType';
import { HttpFile } from '../http/http';

export class CreateOrderItemCommand {
    'quantity': number;
    'type': OrderItemType;
    'status': OrderItemStatus;
    'orderId': string;
    'menuItemId': string;
    'notes'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OrderItemType",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OrderItemStatus",
            "format": ""
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "menuItemId",
            "baseName": "menuItemId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "notes",
            "baseName": "notes",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateOrderItemCommand.attributeTypeMap;
    }

    public constructor() {
    }
}


