/**
 * ReservApp.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimeOnly } from '../models/TimeOnly';
import { HttpFile } from '../http/http';

export class CreateSucursalDto {
    'name': string;
    'address': string;
    'description'?: string | null;
    'phoneNumber': string;
    'isOpen'?: boolean;
    'openTime'?: TimeOnly;
    'closeTime'?: TimeOnly;
    'latitude'?: number;
    'longitude'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "isOpen",
            "baseName": "isOpen",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "openTime",
            "baseName": "openTime",
            "type": "TimeOnly",
            "format": ""
        },
        {
            "name": "closeTime",
            "baseName": "closeTime",
            "type": "TimeOnly",
            "format": ""
        },
        {
            "name": "latitude",
            "baseName": "latitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "longitude",
            "baseName": "longitude",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return CreateSucursalDto.attributeTypeMap;
    }

    public constructor() {
    }
}
