/**
 * ReservApp.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateSucursalDto } from '../models/CreateSucursalDto';
import { HttpFile } from '../http/http';

export class CreateRestaurantCommand {
    'name': string;
    'description'?: string | null;
    'ownerId'?: string;
    'sucursals'?: Array<CreateSucursalDto> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sucursals",
            "baseName": "sucursals",
            "type": "Array<CreateSucursalDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateRestaurantCommand.attributeTypeMap;
    }

    public constructor() {
    }
}
