/**
 * ReservApp.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OrderItemViewModel } from '../models/OrderItemViewModel';
import { OrderStatus } from '../models/OrderStatus';
import { OrderType } from '../models/OrderType';
import { HttpFile } from '../http/http';

export class OrderViewModel {
    'id'?: string;
    'customerId'?: string | null;
    'orderType'?: OrderType;
    'tableNumber'?: number | null;
    'deliveryAddress'?: string | null;
    'items'?: Array<OrderItemViewModel> | null;
    'total'?: number;
    'isPaid'?: boolean;
    'status'?: OrderStatus;
    'approvedByAdmin'?: boolean | null;
    'sucursalId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "OrderType",
            "format": ""
        },
        {
            "name": "tableNumber",
            "baseName": "tableNumber",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "deliveryAddress",
            "baseName": "deliveryAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<OrderItemViewModel>",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": "double"
        },
        {
            "name": "isPaid",
            "baseName": "isPaid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "OrderStatus",
            "format": ""
        },
        {
            "name": "approvedByAdmin",
            "baseName": "approvedByAdmin",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "sucursalId",
            "baseName": "sucursalId",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return OrderViewModel.attributeTypeMap;
    }

    public constructor() {
    }
}


