/**
 * ReservApp.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SucursalViewModel } from '../models/SucursalViewModel';
import { HttpFile } from '../http/http';

export class RestaurantViewModel {
    'id'?: string;
    'name'?: string | null;
    'description'?: string | null;
    'sucursalCount'?: number;
    'ownerId'?: string | null;
    'sucursals'?: Array<SucursalViewModel> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "sucursalCount",
            "baseName": "sucursalCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "sucursals",
            "baseName": "sucursals",
            "type": "Array<SucursalViewModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RestaurantViewModel.attributeTypeMap;
    }

    public constructor() {
    }
}
