/**
 * ReservApp.Web
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TimeOnly {
    'hour'?: number;
    'minute'?: number;
    'second'?: number;
    'millisecond'?: number;
    'microsecond'?: number;
    'nanosecond'?: number;
    'ticks'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hour",
            "baseName": "hour",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "minute",
            "baseName": "minute",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "second",
            "baseName": "second",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "millisecond",
            "baseName": "millisecond",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "microsecond",
            "baseName": "microsecond",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "nanosecond",
            "baseName": "nanosecond",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ticks",
            "baseName": "ticks",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return TimeOnly.attributeTypeMap;
    }

    public constructor() {
    }
}
